# Mandatory settings

name: 52 Hikes
description: "Colorado is a beautiful place, but it is easy to get caught up in the rat race. In 2017 I hope to tackle 52 hikes mostly within an hour of the Denver area. Follow me on my journey here."
paginate: 25
paginate_path: "/posts/page/:num/"
url: # add site url http://example.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: www-52hikes-co # Add your Disqus identifier
rss_enabled: true # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: stevenhubertron # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address
  alltrails: steven-hubert # Add your All Trails Profile

# Markdown settings
  markdown: kramdown
  kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    hard_wrap: false
  highlighter: rouge

# Important settings (change at own risk)


assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug
